name: walk_with_god
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  fluttertoast: ^3.1.3
  intl:
  url_launcher: ^5.4.11
  flutter_visibility_aware: ^0.0.2+1
  modal_bottom_sheet:
  provider: ^4.3.2
  palette_generator:
  auto_size_text: 
  international_phone_input: 
  flutter_auth_buttons: 
  flutter_spinkit:
  google_sign_in:
  apple_sign_in: ^0.1.0
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+7
  wakelock: ^0.1.4+2
  flutter_switch: ^0.1.1
  package_info: ^0.4.3
  path_provider: ^1.6.14
  cached_network_image: ^2.3.2+1
  flutter_cache_manager: ^1.4.2
  connectivity: ^0.4.9+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/images/logo.png
   - assets/images/icon.jpeg
   - assets/images/placeholder.png
   - assets/images/default_profile_picture.jpg
   - assets/images/wechat.png
   - assets/images/friends_circle.png
   - assets/images/facebook.png
   - assets/images/email.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
    - family: Song
      fonts:
        - asset: fonts/LingDongQiCheChunTang-2.ttf
    - family: Jinling
      fonts:
        - asset: fonts/FZCUJINLJW--GB1-0.ttf
    - family: Lanting
      fonts:
        - asset: fonts/FZLTZHK_GBK1_0.ttf
    - family: LantingXianHei
      fonts:
        - asset: fonts/FZLTXHK--GBK1-0.TTF      
    - family: FangzhengTeYaSong
      fonts:
        - asset: fonts/FZTYSFW--GB1-0.ttf        
    - family: HelveticaNeue
      fonts:
        - asset: fonts/HelveticaNeueBold.ttf
          weight: 700
        - asset: fonts/HelveticaNeueHeavy.otf
          weight: 500
        - asset: fonts/HelveticaNeueMedium.ttf
          weight: 300
        - asset: fonts/HelveticaNeueUltraLight.ttf
          weight: 200

          
